# Generated by Django 5.2.5 on 2025-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='id',
            field=models.CharField(default='e302df22784545599a6cd7ca4fa10bf5', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='ae4138e8d99d4ed0be8ad52b72dbb112', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
