# Generated by Django 5.2.5 on 2025-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_alter_bomitem_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='id',
            field=models.CharField(default='db6992c0ec4140dd87dcaba48d162a33', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='aa6b9cbad8d348dc97cdca88a8a5bc90', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
