# Generated by Django 5.2.5 on 2025-10-14 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_alter_bomitem_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5250f276-eb9e-46e0-b764-23919b11ba7d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a83db9b4-8967-45d5-9a70-1abe09e6a286'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
