# Generated by Django 5.2.5 on 2025-10-14 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_alter_bomitem_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f44a375f-1958-44d8-8999-66662297af0f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d79b0a4-6277-4138-acfb-0545d75ffb9a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
