# Generated by Django 5.2.5 on 2025-10-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0006_alter_bomitem_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomitem',
            old_name='component',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='bomitem',
            old_name='product',
            new_name='pid',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='parent',
        ),
    ]
