# Generated by Django 5.2.5 on 2025-10-18 10:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0007_rename_component_bomitem_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
