# Generated by Django 5.2.5 on 2025-10-22 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0008_alter_bomitem_quantity'),
        ('mparts', '0009_rename_title_mpart_code_remove_mpart_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='mparts.mpart'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='mparts.mpart'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
