# Generated by Django 5.2.5 on 2026-03-02 03:44

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_bomitem_created_time_bomitem_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomitem',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='mpart',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
