# Generated by Django 5.2.5 on 2025-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.CharField(default='17d6781236de42e38eb297dc2f650cf6', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.CharField(default='22a216cd66a241bc8f53a56a98a1ab59', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
