# Generated by Django 5.2.5 on 2025-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mparts', '0002_alter_files_id_alter_mpart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.CharField(default='6101b9e9582e415e9e3b01075cad003b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.CharField(default='f4f05ed040ce48c6b00e29f79f91b25c', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
