# Generated by Django 5.2.5 on 2025-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mparts', '0003_alter_files_id_alter_mpart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.CharField(default='05f3dcc472dd430bbbcaac40fd114bde', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.CharField(default='b9b9705fa3c9413e9e728887d348a011', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
