# Generated by Django 5.2.5 on 2025-10-14 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mparts', '0004_alter_files_id_alter_mpart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de0686bc-e48b-4d1f-b035-ae7ed06e8896'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6744172c-5d11-428c-838a-ff48b7e76ccd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
