# Generated by Django 5.2.5 on 2025-10-14 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mparts', '0005_alter_files_id_alter_mpart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb63b3a6-5355-4c6d-8198-64556ee46f3a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af645999-bdc6-4c86-9825-73b5c3f48213'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
