# Generated by Django 5.2.5 on 2025-10-18 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mparts', '0006_alter_files_id_alter_mpart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4b85278-15b5-4e5c-91a8-1a9094fbfc77'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9aa5a7c5-0239-4529-95e4-521190e65d99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
