# Generated by Django 5.2.5 on 2025-10-18 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mparts', '0007_alter_files_id_alter_mpart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9e2f296-9955-40c6-b600-7d1f272e95ec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce78c6de-8610-4415-b5e5-1d7ab5fd17b9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
