# Generated by Django 5.2.5 on 2025-10-22 03:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mparts', '0008_alter_files_id_alter_mpart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpart',
            old_name='title',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='mpart',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mpart',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='mpart',
            name='created_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpart',
            name='name',
            field=models.CharField(default='Unnamed', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpart',
            name='unit',
            field=models.CharField(default='pcs', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ca00538-ec66-424a-a793-65a1b85b913e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mpart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4c86b6f-5cbe-40c8-8f66-fbc2e35c6146'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
