# Generated by Django 5.2.5 on 2026-03-01 07:39

import django.db.models.deletion
import shortuuid.main
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mpart',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('services', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('file', models.FileField(null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='files/')),
                ('mpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='production.mpart')),
            ],
        ),
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='production.mpart')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='production.mpart')),
            ],
        ),
    ]
